version: '3.8'

services:

  db: 
    image: mysql:latest
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: letsBuld@games
      MYSQL_DATABASE: game

    ports: 
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p", "letsBuld@games"]
      interval: 20s
      retries: 10
      start_period: 30s
      timeout: 20s

  app: 
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST = db
      - DB_USER = root
      - DB_PASSWORD = letsBuld@games
      - DB_NAME = game
      - DB_PORT = 3306

volumes:
  db_data: